/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [CredentialNumber]
      ,[LastName]
      ,[FirstName]
      ,[MiddleName]
      ,[CredentialType]
      ,[Status]
      ,[BirthYear]
      ,[CEDueDate]
      ,[FirstIssueDate]
      ,[LastIssueDate]
      ,[ExpirationDate]
      ,[ActionTaken]
  FROM [bcp].[dbo].[Health_Care_Provider_Credential]