USE DWBI;


-- Creating Staging table to load the COVID-19 Nursing Home Dataset
CREATE TABLE Stg_COVID19_NHD
	(
		Week_Ending																				VARCHAR(8000),
		Federal_Provider_Number                                                                 VARCHAR(8000),
		Provider_Name                                                                           VARCHAR(8000),
		Provider_Address                                                                        VARCHAR(8000),
		Provider_City                                                                           VARCHAR(8000),
		Provider_State                                                                          VARCHAR(8000),
		Provider_Zip_Code                                                                       VARCHAR(8000),
		Submitted_Data                                                                          VARCHAR(8000),
		Passed_Quality_Assurance_Check                                                          VARCHAR(8000),
		Residents_Weekly_Admissions_COVID_19                                                    VARCHAR(8000),
		Residents_Total_Admissions_COVID_19                                                     VARCHAR(8000),
		Residents_Weekly_Confirmed_COVID_19                                                     VARCHAR(8000),
		Residents_Total_Confirmed_COVID_19                                                      VARCHAR(8000),
		Residents_Weekly_Suspected_COVID_19                                                     VARCHAR(8000),
		Residents_Total_Suspected_COVID_19                                                      VARCHAR(8000),
		Residents_Weekly_All_Deaths                                                             VARCHAR(8000),
		Residents_Total_All_Deaths                                                              VARCHAR(8000),
		Residents_Weekly_COVID_19_Deaths                                                        VARCHAR(8000),
		Residents_Total_COVID_19_Deaths                                                         VARCHAR(8000),
		Number_of_All_Beds                                                                      VARCHAR(8000),
		Total_Number_of_Occupied_Beds                                                           VARCHAR(8000),
		Resident_Access_to_Testing_in_Facility                                                  VARCHAR(8000),
		Laboratory_Type_Is_State_Health_Dept                                                    VARCHAR(8000),
		Laboratory_Type_Is_Private_Lab                                                          VARCHAR(8000),
		Laboratory_Type_Is_Other                                                                VARCHAR(8000),
		Able_to_Test_or_Obtain_Resources_to_Test_All_Current_Residents_Within_Next_7_Days       VARCHAR(8000),
		Reason_for_Not_Testing_Residents_Lack_of_PPE_for_Personnel                              VARCHAR(8000),
		Reason_for_Not_Testing_Residents_Lack_of_Supplies                                       VARCHAR(8000),
		Reason_for_Not_Testing_Residents_Lack_of_Access_to_Laboratory                           VARCHAR(8000),
		Reason_for_Not_Testing_Residents_Lack_of_Access_to_Trained_Personnel                    VARCHAR(8000),
		Reason_for_Not_Testing_Residents_Uncertainty_About_Reimbursement                        VARCHAR(8000),
		Reason_for_Not_Testing_Residents_Other                                                  VARCHAR(8000),
		During_Past_Two_Weeks_Average_Time_to_Receive_Resident_Test_Results                     VARCHAR(8000),
		Has_Facility_Performed_Resident_Tests_Since_Last_Report                                 VARCHAR(8000),
		Tested_Residents_with_New_Signs_or_Symptoms                                             VARCHAR(8000),
		Tested_Asymptomatic_Residents_in_a_Unit_or_Section_After_a_New_Case                     VARCHAR(8000),
		Tested_Asymptomatic_Residents_Facility_Wide_After_a_New_Case                            VARCHAR(8000),
		Tested_Asymptomatic_Residents_Without_Known_Exposure_as_Surveillance                    VARCHAR(8000),
		Tested_Another_Subgroup_of_Residents                                                    VARCHAR(8000),
		Able_to_Test_or_Obtain_Resources_to_Test_All_Staff_and_or_Personnel_Within_Next_7_Days  VARCHAR(8000),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Lack_of_PPE_for_Personnel                 VARCHAR(8000),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Lack_of_Supplies                          VARCHAR(8000),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Lack_of_Access_to_Laboratory              VARCHAR(8000),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Lack_of_Access_to_Trained_Personnel       VARCHAR(8000),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Uncertainty_About_Reimbursement           VARCHAR(8000),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Other                                     VARCHAR(8000),
		During_Past_Two_Weeks_Average_Time_to_Receive_Staff_and_or_Personnel_Test_Results       VARCHAR(8000),
		Has_Facility_Performed_Staff_and_or_Personnel_Tests_Since_Last_Report                   VARCHAR(8000),
		Tested_Staff_and_or_Personnel_with_New_Signs_or_Symptoms                                VARCHAR(8000),
		Tested_Asymptomatic_Staff_and_or_Personnel_in_a_Unit_or_Section_After_a_New_Case        VARCHAR(8000),
		Tested_Asymptomatic_Staff_and_or_Personnel_Facility_Wide_After_a_New_Case               VARCHAR(8000),
		Tested_Asymptomatic_Staff_and_or_Personnel_Without_Known_Exposure_as_Surveillance       VARCHAR(8000),
		Tested_Another_Subgroup_of_Staff_and_or_Personnel                                       VARCHAR(8000),
		In_House_Point_of_Care_Test_Machine                                                     VARCHAR(8000),
		COVID_19_Point_of_Care_Tests_Performed_on_Residents_Since_Last_Report                   VARCHAR(8000),
		COVID_19_Point_of_Care_Tests_Performed_on_Staff_and_or_Personnel_Since_Last_Report      VARCHAR(8000),
		Enough_Supplies_to_Test_All_Staff_and_or_Personnel_Using_Point_of_Care_Test_Machine     VARCHAR(8000),
		Staff_Weekly_Confirmed_COVID_19                                                         VARCHAR(8000),
		Staff_Total_Confirmed_COVID_19                                                          VARCHAR(8000),
		Staff_Weekly_Suspected_COVID_19                                                         VARCHAR(8000),
		Staff_Total_Suspected_COVID_19                                                          VARCHAR(8000),
		Staff_Weekly_COVID_19_Deaths                                                            VARCHAR(8000),
		Staff_Total_COVID_19_Deaths                                                             VARCHAR(8000),
		Shortage_of_Nursing_Staff                                                               VARCHAR(8000),
		Shortage_of_Clinical_Staff                                                              VARCHAR(8000),
		Shortage_of_Aides                                                                       VARCHAR(8000),
		Shortage_of_Other_Staff                                                                 VARCHAR(8000),
		Any_Current_Supply_of_N95_Masks                                                         VARCHAR(8000),
		One_Week_Supply_of_N95_Masks                                                            VARCHAR(8000),
		Any_Current_Supply_of_Surgical_Masks                                                    VARCHAR(8000),
		One_Week_Supply_of_Surgical_Masks                                                       VARCHAR(8000),
		Any_Current_Supply_of_Eye_Protection                                                    VARCHAR(8000),
		One_Week_Supply_of_Eye_Protection                                                       VARCHAR(8000),
		Any_Current_Supply_of_Gowns                                                             VARCHAR(8000),
		One_Week_Supply_of_Gowns                                                                VARCHAR(8000),
		Any_Current_Supply_of_Gloves                                                            VARCHAR(8000),
		One_Week_Supply_of_Gloves                                                               VARCHAR(8000),
		Any_Current_Supply_of_Hand_Sanitizer                                                    VARCHAR(8000),
		One_Week_Supply_of_Hand_Sanitizer                                                       VARCHAR(8000),
		Ventilator_Dependent_Unit                                                               VARCHAR(8000),
		Number_of_Ventilators_in_Facility                                                       VARCHAR(8000),
		Number_of_Ventilators_in_Use_for_COVID_19                                               VARCHAR(8000),
		Any_Current_Supply_of_Ventilator_Supplies                                               VARCHAR(8000),
		One_Week_Supply_of_Ventilator_Supplies                                                  VARCHAR(8000),
		weekly_resident_confirmed_covid_19_cases_per_1_000_residents							VARCHAR(8000),
		weekly_resident_covid_19_deaths_per_1_000_residents									    VARCHAR(8000),
		Total_Resident_Confirmed_COVID_19_Cases_Per_1000_Residents                              VARCHAR(8000),
		Total_Resident_COVID_19_Deaths_Per_1000_Residents                                       VARCHAR(8000),
		Total_Residents_COVID_19_Deaths_as_a_Percentage_of_Confirmed_COVID_19_Cases             VARCHAR(8000),
		County                                                                                  VARCHAR(8000),
		Three_or_More_Confirmed_COVID_19_Cases_This_Week                                        VARCHAR(8000),
		Initial_Confirmed_COVID_19_Case_This_Week                                               VARCHAR(8000),
		Geolocation 																			VARCHAR(8000),
		reporting_interval																	    VARCHAR(8000)
	);


-- Drop statement to drop table incase of any errors
DROP TABLE Stg_COVID19_NHD;


-- Creating Destination table to load the COVID-19 Nursing Home Dataset with proper datatypes with the help of Talend Profiling
CREATE TABLE Dst_COVID19_NHD_Talend
	(
		Week_Ending																				DATE,
		Federal_Provider_Number                                                                 VARCHAR(9),
		Provider_Name                                                                           VARCHAR(53),
		Provider_Address                                                                        VARCHAR(51),
		Provider_City                                                                           VARCHAR(20),
		Provider_State                                                                          CHAR(2),
		Provider_Zip_Code                                                                       VARCHAR(5),
		Submitted_Data                                                                          CHAR(1),
		Passed_Quality_Assurance_Check                                                          CHAR(1),
		Residents_Weekly_Admissions_COVID_19                                                    INT,
		Residents_Total_Admissions_COVID_19                                                     INT,
		Residents_Weekly_Confirmed_COVID_19                                                     INT,
		Residents_Total_Confirmed_COVID_19                                                      INT,
		Residents_Weekly_Suspected_COVID_19                                                     INT,
		Residents_Total_Suspected_COVID_19                                                      INT,
		Residents_Weekly_All_Deaths                                                             INT,
		Residents_Total_All_Deaths                                                              INT,
		Residents_Weekly_COVID_19_Deaths                                                        INT,
		Residents_Total_COVID_19_Deaths                                                         INT,
		Number_of_All_Beds                                                                      INT,
		Total_Number_of_Occupied_Beds                                                           INT,
		Resident_Access_to_Testing_in_Facility                                                  CHAR(1),
		Laboratory_Type_Is_State_Health_Dept                                                    CHAR(1),
		Laboratory_Type_Is_Private_Lab                                                          CHAR(1),
		Laboratory_Type_Is_Other                                                                CHAR(1),
		Able_to_Test_or_Obtain_Resources_to_Test_All_Current_Residents_Within_Next_7_Days       CHAR(1),
		Reason_for_Not_Testing_Residents_Lack_of_PPE_for_Personnel                              CHAR(1),
		Reason_for_Not_Testing_Residents_Lack_of_Supplies                                       CHAR(1),
		Reason_for_Not_Testing_Residents_Lack_of_Access_to_Laboratory                           CHAR(1),
		Reason_for_Not_Testing_Residents_Lack_of_Access_to_Trained_Personnel                    CHAR(1),
		Reason_for_Not_Testing_Residents_Uncertainty_About_Reimbursement                        CHAR(1),
		Reason_for_Not_Testing_Residents_Other                                                  CHAR(1),
		During_Past_Two_Weeks_Average_Time_to_Receive_Resident_Test_Results                     VARCHAR(8),
		Has_Facility_Performed_Resident_Tests_Since_Last_Report                                 CHAR(1),
		Tested_Residents_with_New_Signs_or_Symptoms                                             CHAR(1),
		Tested_Asymptomatic_Residents_in_a_Unit_or_Section_After_a_New_Case                     CHAR(1),
		Tested_Asymptomatic_Residents_Facility_Wide_After_a_New_Case                            CHAR(1),
		Tested_Asymptomatic_Residents_Without_Known_Exposure_as_Surveillance                    CHAR(1),
		Tested_Another_Subgroup_of_Residents                                                    CHAR(1),
		Able_to_Test_or_Obtain_Resources_to_Test_All_Staff_and_or_Personnel_Within_Next_7_Days  CHAR(1),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Lack_of_PPE_for_Personnel                 CHAR(1),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Lack_of_Supplies                          CHAR(1),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Lack_of_Access_to_Laboratory              CHAR(1),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Lack_of_Access_to_Trained_Personnel       CHAR(1),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Uncertainty_About_Reimbursement           CHAR(1),
		Reason_for_Not_Testing_Staff_and_or_Personnel_Other                                     CHAR(1),
		During_Past_Two_Weeks_Average_Time_to_Receive_Staff_and_or_Personnel_Test_Results       VARCHAR(8),
		Has_Facility_Performed_Staff_and_or_Personnel_Tests_Since_Last_Report                   CHAR(1),
		Tested_Staff_and_or_Personnel_with_New_Signs_or_Symptoms                                CHAR(1),
		Tested_Asymptomatic_Staff_and_or_Personnel_in_a_Unit_or_Section_After_a_New_Case        CHAR(1),
		Tested_Asymptomatic_Staff_and_or_Personnel_Facility_Wide_After_a_New_Case               CHAR(1),
		Tested_Asymptomatic_Staff_and_or_Personnel_Without_Known_Exposure_as_Surveillance       CHAR(1),
		Tested_Another_Subgroup_of_Staff_and_or_Personnel                                       CHAR(1),
		In_House_Point_of_Care_Test_Machine                                                     CHAR(1),
		COVID_19_Point_of_Care_Tests_Performed_on_Residents_Since_Last_Report                   INT,
		COVID_19_Point_of_Care_Tests_Performed_on_Staff_and_or_Personnel_Since_Last_Report      INT,
		Enough_Supplies_to_Test_All_Staff_and_or_Personnel_Using_Point_of_Care_Test_Machine     CHAR(1),
		Staff_Weekly_Confirmed_COVID_19                                                         INT,
		Staff_Total_Confirmed_COVID_19                                                          INT,
		Staff_Weekly_Suspected_COVID_19                                                         INT,
		Staff_Total_Suspected_COVID_19                                                          INT,
		Staff_Weekly_COVID_19_Deaths                                                            INT,
		Staff_Total_COVID_19_Deaths                                                             INT,
		Shortage_of_Nursing_Staff                                                               CHAR(1),
		Shortage_of_Clinical_Staff                                                              CHAR(1),
		Shortage_of_Aides                                                                       CHAR(1),
		Shortage_of_Other_Staff                                                                 CHAR(1),
		Any_Current_Supply_of_N95_Masks                                                         CHAR(1),
		One_Week_Supply_of_N95_Masks                                                            CHAR(1),
		Any_Current_Supply_of_Surgical_Masks                                                    CHAR(1),
		One_Week_Supply_of_Surgical_Masks                                                       CHAR(1),
		Any_Current_Supply_of_Eye_Protection                                                    CHAR(1),
		One_Week_Supply_of_Eye_Protection                                                       CHAR(1),
		Any_Current_Supply_of_Gowns                                                             CHAR(1),
		One_Week_Supply_of_Gowns                                                                CHAR(1),
		Any_Current_Supply_of_Gloves                                                            CHAR(1),
		One_Week_Supply_of_Gloves                                                               CHAR(1),
		Any_Current_Supply_of_Hand_Sanitizer                                                    CHAR(1),
		One_Week_Supply_of_Hand_Sanitizer                                                       CHAR(1),
		Ventilator_Dependent_Unit                                                               CHAR(1),
		Number_of_Ventilators_in_Facility                                                       INT,
		Number_of_Ventilators_in_Use_for_COVID_19                                               INT,
		Any_Current_Supply_of_Ventilator_Supplies                                               CHAR(1),
		One_Week_Supply_of_Ventilator_Supplies                                                  CHAR(1),
		weekly_resident_confirmed_covid_19_cases_per_1_000_residents							BIGINT,
		weekly_resident_covid_19_deaths_per_1_000_residents										BIGINT,
		Total_Resident_Confirmed_COVID_19_Cases_Per_1000_Residents                              BIGINT,
		Total_Resident_COVID_19_Deaths_Per_1000_Residents                                       BIGINT,
		Total_Residents_COVID_19_Deaths_as_a_Percentage_of_Confirmed_COVID_19_Cases             BIGINT,
		County                                                                                  VARCHAR(23),
		Three_or_More_Confirmed_COVID_19_Cases_This_Week                                        CHAR(1),
		Initial_Confirmed_COVID_19_Case_This_Week                                               CHAR(1),
		Geolocation 																			VARCHAR(46),
		reporting_interval																		VARCHAR(16)
	);


-- Drop statement to drop table incase of any errors
DROP TABLE Dst_COVID19_NHD_Talend;


--Select statement to select the entire dataset
SELECT * FROM Stg_COVID19_NHD;

SELECT * FROM Dst_COVID19_NHD_Talend;